### ISSUE TITLE
Create UI on Figma

### ISSUE THREAD

**Issue by kaiwalyakoparkar** [kaiwalyakoparkar/quora-for-college#20]
Design Link: https://www.figma.com/file/Bi8YxKfn9z3mg7j5nR0SHk/Desktop-Design-for-Quora-for-College?node-id=0%3A1

**Comment by vadanyawabale** [comment]
i can do this

**Comment by kaiwalyakoparkar** [comment]
Thanks for interest @vadanyawabale but this is already been done. You can choose another issue (even if it's taken)
