### ISSUE TITLE
[BUG]  LowerCase the issue start tag (eg: `[BUG]` , `[FEATURE]` )

### ISSUE THREAD

**Issue by kaiwalyakoparkar** [kaiwalyakoparkar/quora-for-college#22]

**Comment by mrunaal20** [comment]
Hello, how can I help you?

**Comment by kaiwalyakoparkar** [comment]
Assigned you the issue:
Change to [feat] : https://github.com/kaiwalyakoparkar/quora-for-college/edit/main/.github/ISSUE_TEMPLATE/feature_request.yml **(Line no 3)**
Change to [bug] : https://github.com/kaiwalyakoparkar/quora-for-college/edit/main/.github/ISSUE_TEMPLATE/bug_report.yml **(Line no 3)**
Change to [docs] : https://github.com/kaiwalyakoparkar/quora-for-college/blob/main/.github/ISSUE_TEMPLATE/doc_report.yml#L3
Change to [other] : https://github.com/kaiwalyakoparkar/quora-for-college/edit/main/.github/ISSUE_TEMPLATE/other.yml **(Line no 3)**
