### ISSUE TITLE
[docs] Main project (Root) folder documentation

### ISSUE THREAD

**Issue by kaiwalyakoparkar** [kaiwalyakoparkar/quora-for-college#41]
### What would you like to share?

Please add root documentation

**Comment by mrunaal20** [comment]
Hey assign me so that I can contribute in this issue.

**Comment by Kannav02** [comment]
Hey! has this issue been fixed , if not can I contribute to it?

**Comment by Kannav02** [comment]
Oh ok

**Comment by pragatimore764** [comment]
can I contribute to it

**Comment by kaiwalyakoparkar** [comment]
@pragatimore764 Sure
