### ISSUE TITLE
[feat] Add additional sample data for questions and answers

### ISSUE THREAD

**Issue by kaiwalyakoparkar** [kaiwalyakoparkar/quora-for-college#43]
### Would you like to have a new feature? Please describe.

Please go to `server/data/dev-data/questions.json` and add more questions and answers from previous examples

**Comment by ShivamTyagi12345** [comment]
helping with this issue. /assign

**Comment by kaiwalyakoparkar** [comment]
Sorry @ShivamTyagi12345 I won't be able to assign it to you as it is a college project. We will be accepting outer contributions from August 2022

**Comment by mrunaal20** [comment]
Hey assign me so that I can contribute in this issue.

**Comment by vadanyawabale** [comment]
i would like to work on this

**Comment by pragatimore764** [comment]
Hey assign me so that I can contribute in this issue!
