### ISSUE TITLE
[bug] Different project name in `start.js`

### ISSUE THREAD

**Issue by kaiwalyakoparkar** [kaiwalyakoparkar/quora-for-college#59]
### Describe the bug

The project name is different (As script was copied from a old project). The task is to replace `LearnScape` text on (https://github.com/kaiwalyakoparkar/quora-for-college/blob/main/start.js#L42)[https://github.com/kaiwalyakoparkar/quora-for-college/blob/main/start.js#L42] line with `QuFoCo` (Short form of Quora for College)

**Comment by pragatimore764** [comment]
I would like to work on issue/project!

**Comment by pragatimore764** [comment]
i would like to work on this issue/project!

**Comment by mrunaal20** [comment]
I would like to contribute:)
