### ISSUE TITLE
[bug] Update the kubernetes deployment config with the published container image.

### ISSUE THREAD

**Issue by kaiwalyakoparkar** [kaiwalyakoparkar/quora-for-college#71]

**Comment by RishiKumarRay** [comment]
Can you explain where to do this , I would like to give a try

**Comment by kaiwalyakoparkar** [comment]
Hey, @RishiKumarRay Thank you so much for your interest in contributing. But currently, this is a college project so we would be accepting outer contributions after August 2022.
