### ISSUE TITLE
[docs] Add inspiration to the server documentation

### ISSUE THREAD

**Issue by kaiwalyakoparkar** [kaiwalyakoparkar/quora-for-college#74]
### Category of documentation update

Take the abstract section from the report submitted and place it under inspiration section

**Comment by mrunaal20** [comment]
Hey! assign me:)

**Comment by kaiwalyakoparkar** [comment]
@mrunaal20 Done, Let me know if you need any help

**Comment by mrunaal20** [comment]
@kaiwalyakoparkar  sure👍

**Comment by pragatimore764** [comment]
Hey assign me so that I can contribute in this issue!

**Comment by vadanyawabale** [comment]
hey assign me

**Comment by kaiwalyakoparkar** [comment]
Hey @pragatimore764 & @vadanyawabale This issue is already been solved by @mrunaal20 #76
